apiVersion: v1
kind: ConfigMap
metadata:
  name: razorpay-config
  namespace: razorpay
data:
  CONFIG_SERVER_URL: "http://config-service:8888"
  EUREKA_DEFAULT_ZONE: "http://discovery-service:8761/eureka/"
  ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  REDIS_HOST: "redis"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  DB_USERNAME: "postgres"
  MERCHANT_SERVICE_URL: "http://merchant-service:8081"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
