apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: razorpay

resources:
  - namespace.yaml
  - config.yaml
  - infra/postgres.yaml
  - infra/redis.yaml
  - infra/kafka.yaml
  - infra/zipkin.yaml
  - services/discovery-service.yaml
  - services/config-service.yaml
  - services/merchant-service.yaml
  - services/vault-service.yaml
  - services/payment-service.yaml
  - services/operations-service.yaml
  - services/api-gateway-service.yaml

secretGenerator:
  - name: app-secrets
    envs:
      - secrets.env

generatorOptions:
  disableNameSuffixHash: true
